Repository golangci/golangci-lint-action, pull requests merged in 2022-02, with the labels that each got.

#351 Allow to disable caching completely
  README.md
  action.yml
  dist/post_run/index.js
  dist/run/index.js
  src/cache.ts
Labels: enhancement

#108 ci(dep): Add step to commit changes if PR has dependencies label
  .github/workflows/test.yml
Labels: dependencies, hacktoberfest, hacktoberfest-accepted

#407 fix version in package-lock.json
  package-lock.json
Labels: bug
