Repository golangci/golangci-lint-action, pull requests merged in 2023-06, with the labels that each got.

#762 docs: fix example
  README.md
Labels: bug, documentation

#767 doc: Add custom configuration file path to args
  README.md
Labels: documentation

#768 feat: add install-mode
  .github/workflows/test.yml
  README.md
  action.yml
  dist/post_run/index.js
  dist/run/index.js
  src/install.ts
  src/run.ts
  src/version.ts
Labels: enhancement

#769 feat: support out-format as args
  dist/post_run/index.js
  dist/run/index.js
  src/run.ts
Labels: enhancement

#770 fix: out-format
  dist/post_run/index.js
  dist/run/index.js
  src/run.ts
Labels: bug

#780 docs: improve `How to use` section in README.md
  README.md
Labels: documentation
