Repository golangci/golangci-lint-action, pull requests merged in 2025-05, with the labels that each got.

#1230 docs: clarify that ’args: --path-mode=abs’ is needed for working-directory
  README.md
Labels: documentation, enhancement

#1231 feat: use absolute paths by default when using working-directory option
  .github/workflows/test.yml
  README.md
  dist/post_run/index.js
  dist/run/index.js
  sample-go-mod/go.mod
  sample-go-mod/go.sum
  sample-go-tool/go.mod
  sample-go-tool/go.sum
  src/run.ts
  src/version.ts
Labels: enhancement, area: output

#1242 docs: improve options description and README
  README.md
  action.yml
Labels: documentation
