Repository golangci/golangci-lint-action, pull requests merged in 2025-02, with the labels that each got.

#1158 fix: restrict patched version to v1
  dist/post_run/index.js
  dist/run/index.js
  package-lock.json
  package.json
  src/install.ts
  src/run.ts
  src/version.ts
Labels: topic: cleanup

#1159 chore: update golangci-lint versions
  .github/workflows/test.yml
Labels: topic: cleanup

#1165 fix: go.mod parsing
  .github/workflows/test.yml
  dist/post_run/index.js
  dist/run/index.js
  sample-go-tool/go.mod
  sample-go-tool/go.sum
  sample-go-tool/sample.go
  src/version.ts
Labels: bug

#1168 fix: use config arg for verify
  dist/post_run/index.js
  dist/run/index.js
  src/run.ts
Labels: bug, area: verify

#1171 feat: verify with the JSONSchema by default
  .github/workflows/test.yml
  action.yml
  dist/post_run/index.js
  dist/run/index.js
  src/run.ts
Labels: enhancement, area: verify

#1173 docs: add notes for annotation config
  README.md
Labels: documentation, enhancement

#1175 docs: improve verify option explanation
  README.md
Labels: documentation
