Repository golangci/golangci-lint-action, pull requests merged in 2025-03, with the labels that each got.

#1193 fix: octokit retry
  dist/post_run/index.js
  dist/run/index.js
  package-lock.json
  package.json
  src/patch.ts
Labels: bug

#1194 feat: restrict action v6 on golangci-lint v1
  dist/post_run/index.js
  dist/run/index.js
  src/version.ts
Labels: area: installation

#1201 fix: update max version
  dist/post_run/index.js
  dist/run/index.js
  src/version.ts
Labels: area: installation

#1203 docs: update annotation permissions
  README.md
Labels: documentation, area: annotations

#1204 docs: fix checks permissions for annotations
  README.md
Labels: documentation

#1198 feat: golangci-lint v2 support
  .github/workflows/test.yml
  .golangci.yml
  README.md
  action.yml
  dist/post_run/index.js
  dist/run/index.js
  go.mod
  sample-go-mod/.golangci.yml
  sample-go-mod/go.mod
  sample-go-mod/tools.go
  sample-go-tool/.golangci.yml
  sample-go-tool/go.mod
  src/install.ts
  src/run.ts
  src/version.ts
Labels: enhancement
